### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Bijay555** [kandelsatish/used_cars#1]
Tasks to follow:
Write proper details regarding the projects, giving an outline and summary of the data science project cycle we follow in the project. 

- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #37

**Comment by TimmieG** [comment]
@bharat444 please see if you can comment here

**Comment by bharat444** [comment]
Yes I can

**Comment by TimmieG** [comment]
Documentation Complete
